### ISSUE TITLE
Minor formatting issue displaying lyrics

### ISSUE THREAD

**Issue by bjclopes** [JoshLmao/Genify#17]
Hello there!
I've checked out your project and I really like how it's coming along! I'm new to GitHub, so I'm not sure if this is the correct way to let you know of this little bug.

I just noticed that sometimes between parts of a song (eg. end of verse 1 and beginning of chorus) there's a double newline or none at all. I believe it happens where the ads used to be, so it probably has a pretty quick and easy fix.

**Comment by JoshLmao** [comment]
Hey! ! You've done the right thing submitting an issue. I've also noticed this myself too so thanks for logging it. I'll get around to fixing it asap

**Comment by JoshLmao** [comment]
This should be fixed now in v3.0.10. Let me know if you ever see it again since it's quite a niche use case

**Comment by bjclopes** [comment]
Hey there! The fix you implemented solved the issue most of the time. I believe I haven't noticed it on desktop, but sometimes it still happens on mobile. The way ads load on mobile might be different.
![IMG_5281](https://user-images.githubusercontent.com/84648158/131248143-15d0a7fc-5c2d-4beb-8a64-283aae76da25.png)
